//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string LH1 = "lh1";
        
        public const string LH5 = "lh5";
        
        public const string RH3 = "rh3";
        
        public const string GAME_START = "game_start";
        
        public const string RH2 = "rh2";
        
        public const string TESTHAND = "testhand";
        
        public const string LH2 = "lh2";
        
        public const string LH3 = "lh3";
        
        public const string LH4 = "lh4";
        
        public const string RH1 = "rh1";
        
        public const string RH4 = "rh4";
        
        public const string TEST = "test";
        
        public const string RH5 = "rh5";
    }
}
